version: "4"
services:

  notificaciones:
    build: 
      context: ./dockerfiles
      dockerfile: notificaciones.dockerfile
    volumes:
      - ./kafka/Notificaciones:/app
    working_dir: /app
    depends_on:
      - kafka
  
  procesamiento:
    build: 
      context: ./dockerfiles
      dockerfile: procesamiento.dockerfile
    volumes:
      - ./kafka/Procesamiento:/app
    working_dir: /app
    depends_on:
      - kafka

  solicitudes:
    build: 
      context: ./dockerfiles
      dockerfile: solicitudes.dockerfile
    volumes:
      - ./kafka/Solicitudes:/app
    working_dir: /app
    depends_on:
      - kafka

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
