<<<<<<< HEAD

services:
  procesamiento:
    build: 
      context: ./kafka/Procesamiento
      dockerfile: Dockerfile
    container_name: Procesamiento
    depends_on:
      - kafka
    restart: always
  
  consumer:
    build: 
      context: ./kafka/Solicitudes-Notificaciones/consumer
      dockerfile: Dockerfile
    container_name: Procesamiento
    depends_on:
      - kafka
    restart: always
  

  producer:
    build: 
      context: ./kafka/Solicitudes-Notificaciones/producer
      dockerfile: Dockerfile
    container_name: Procesamiento
    depends_on:
      - kafka
    restart: always
=======
version: "4"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
>>>>>>> parent of 7bc413f (Ayuda)

    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always
