version: "5"
services:
  solicitudes:
    image: python:latest
    container_name: solicitudes
    volumes:
      - ./kafka/Solicitudes-Notifiaciones/producer:/kafka/Solicitudes-Notifiaciones/producer
    working_dir: ./kafka/Solicitudes-Notifiaciones/producer
    command: /bin/bash -c "./start.sh"
    restart: always

  notificaciones:
    image: python:latest
    container_name: notificaciones
    volumes:
      - ./kafka/Solicitudes-Notifiaciones/consumer:/kafka/Solicitudes-Notifiaciones/consumer
    working_dir: ./kafka/Solicitudes-Notifiaciones/consumer
    command: /bin/bash -c "./start.sh"
    restart: always

  procesamiento:
    image: python:latest
    container_name: procesamiento
    volumes:
      - ./kafka/Procesamiento:/kafka/Procesamiento
    working_dir: ./kafka/Procesamiento
    command: /bin/bash -c "./start.sh"
    restart: always


  kafka:
    image: 'bitnami/kafka:latest'
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: always
